### ISSUE TITLE
Add syntax highlight for other languages

### ISSUE THREAD

**Issue by kumarshantanu** [oakes/Nightlight#15]
People use several kinds of files in a project, e.g. Java, Markdown, HTML, CSS, JavaScript etc. It would be good to have syntax highlight feature for various file types.

**Comment by oakes** [comment]
Yeah this should be fairly easy to do. All non-clojure files are opened with CodeMirror, which has support for syntax highlighting in most langs, I just haven't looked into enabling it yet.

**Comment by oakes** [comment]
Added support for CSS, JS, markdown, sass, shell, sql, and xml/html in f0a5c89b00cd25b698751115e762e1462fe0e663. The codemirror CLJSJS library doesn't provide the java mode so I couldn't add it.
