### ISSUE TITLE
Cursor is not black enough in the light color theme

### ISSUE THREAD

**Issue by kumarshantanu** [oakes/Nightlight#22]
The cursor assumes the same color as the adjacent character in light color theme and is often quite difficult to notice. It would be great to make the cursor thicker and distinctly black-color in the light color theme.

**Comment by oakes** [comment]
Adding `caret-color: black;` to the `.paren-soup` class in `paren-soup-light.css` appears to fix this in chrome, but not in firefox. In the firefox inspector it says "invalid property value", even though [the docs](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color) indicate I'm using it correctly...

**Comment by oakes** [comment]
I added the CSS property I mentioned.
