### ISSUE TITLE
How do I get started with this thing?

### ISSUE THREAD

**Issue by lwb4** [oakes/Nightlight#27]
I added `{:user {:plugins [[nightlight/lein-nightlight "1.6.3"]]}}` to my `~/.lein/profiles.clj`, and tried to run `lein nightlight --port 4000`, but the terminal said `'nightlight' is not a task.`

I am a complete noob to 1) Leiningen, and 2) Clojure. Can you help me out with some kind of absolute beginner's guide? I would like to learn Clojure, and Nightlight sounds like a really interesting project concept.

**Comment by oakes** [comment]
Hmm I can't reproduce this...that is exactly what I have in my profiles.clj. Can you paste the entire output?

**Comment by lwb4** [comment]
It just says `'nightlight' is not a task. run lein help` 

I just ran:

    lein new app clojure-test
    cd clojure-test
    lein nightlight --port 4000

I literally haven't done anything else though. Is that all I'm supposed to do?

**Comment by lwb4** [comment]
Oh, I figured it out. I also had this line in my profiles.clj:

    {:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}

For when I was using CIDER with Emacs, working through Brave Clojure. Interesting.

**Comment by oakes** [comment]
Ah gotcha, yeah you'd have to merge them together.
