### ISSUE TITLE
run in an existing webserver

### ISSUE THREAD

**Issue by nha** [oakes/Nightlight#3]
Feature request: could it be possible to expose a ring handler as part of the API?

This would allow:
-  reuse machine port/resources, no need to start httpkit
- add authentication etc. in the app before calling the ring handler (my particular target would be ring/yada

Thanks for doing this!

**Comment by oakes** [comment]
Very good idea, I'll work on that soon.

**Comment by oakes** [comment]
I moved the final handler to a new var at `nightlight.core/app` in 52af45837a1b570f31b3848dd938e8fc1f7898aa. I'm not that experienced with ring middleware stuff so please let me know if there is more I can do.
