### ISSUE TITLE
REPL Can't find dependencies when using boot

### ISSUE THREAD

**Issue by hswick** [oakes/Nightlight#30]
Trying to use REPL in a pure boot project and am finding that the dependencies are not on the classpath

**Comment by hswick** [comment]
Maybe its possible to inject the dependencies into the repl state on startup

**Comment by hswick** [comment]
Tried similar project with lein and had same problem. Feel like I'm doing something wrong :/

**Comment by hswick** [comment]
Found that this error happens intermittently. Sometimes correct behavior sometimes not, even if nothing changed.

**Comment by oakes** [comment]
Have you used `require` in the REPL to bring them in?

**Comment by hswick** [comment]
So I required all of my dependencies individually and found that I'm having trouble with this one.

(require '[clj-http.client :as client])

I am able to require it in boot repl with no problem.

It gives this error when running in instarepl:
java.lang.Exception: namespace 'clj-http.client' not found, compiling:(NO_SOURCE_PATH:0:0)

**Comment by oakes** [comment]
Is there possibly a sample project I could try that reproduces this?

**Comment by hswick** [comment]
You can view the repo itself there isn't much there 
https://github.com/hswick/import-export

**Comment by oakes** [comment]
@hswick Please check out the pull request I sent to that repo. You need to require your namespace (`import-export.core`) in your build.boot, that way it'll be there when nightlight runs. I also changed that ns to require everything inside the ns form as is typical. If you still notice problems please let me know.
