### ISSUE TITLE
add --host to bind localhost

### ISSUE THREAD

**Issue by dukefong8** [oakes/Nightlight#32]
Hi, first want to say this is so amazing and very useful tool. May I suggest to add --host option (in addtion to --port) to allow binding to localhost. This would make people more conformtable for remote server use case by ssh tunneling (ssh -L). Though user/password protect it to certain degree, but they are clear text in transite on the network. As --host localhost won't expose --port on network and people typical have ssh access to their server, non-encrypted nightlight http trafic can be encrypted in side of ssh connection.

**Comment by oakes** [comment]
Just added this feature in d014eb433220dd301199172c7cd5c087b8ec3ba0, thanks!

**Comment by oakes** [comment]
I released 1.6.5 with this feature and added an explanation on the web page of how to use it, FYI.

**Comment by dukefong8** [comment]
Great. Thanks!
