### ISSUE TITLE
.gitignore files are not visible

### ISSUE THREAD

**Issue by hswick** [oakes/Nightlight#33]
Nightlight doesn't seem to include .gitignore files in the available directory tree

**Comment by oakes** [comment]
Currently it does not show any hidden files or directories.

**Comment by hswick** [comment]
Gotcha. I had to use another editor to edit my .gitignore file and thought I should report.

Is this a hopeful feature in the future? Feel like it might be tricky if the editor is being hosted.

**Comment by oakes** [comment]
Not showing hidden files is intentional. I'll put some thought into it though, since it may be better to just show them.
