### ISSUE TITLE
Can't view/edit visible .edn or .json 

### ISSUE THREAD

**Issue by hswick** [oakes/Nightlight#34]
Created new file within nightlight called config.edn. Opened in Nightlight and no cursor or line numbers on side. 

Edited the file with different editor, reopened and none of the data was visible. File does show up in left sidebar directory tree so file is not hidden. However, unable to view or edit.

**Comment by oakes** [comment]
Wow, this is definitely a problem. I fixed it in 4d90bf6a600ba1ce189deca175fbe8706db3e68d, thanks.

**Comment by oakes** [comment]
I just released 1.6.5 with this fix, FYI.
