### ISSUE TITLE
suport for secure WS

### ISSUE THREAD

**Issue by fbellomi** [oakes/Nightlight#4]
First of all, thanks for this wonderful project.

Feature request: I would like to use it on an app deployed under https; this makes mandatory to make the repl work under a secure web socket.

My understanding is that the only needed change would be to allow to use "wss://" instead of "ws://" in nightlight.editors/ps-repl-init

thanks, Francesco

**Comment by oakes** [comment]
Fixed in 4dce06b4a6da1d591ce22da1dfc9ceea9413ce69, thanks!

**Comment by fbellomi** [comment]
Great! Thanks!

Francesco
