### ISSUE TITLE
REPL not starting in -main namespace

### ISSUE THREAD

**Issue by cakenggt** [oakes/Nightlight#40]
When I create a new app and run nightlight in it with lein, the Clojure REPL starts in `clojure.core`, not in the namespace with the `-main` function.

Steps:
1. Run `lein new app test-app`
2. cd into new directory `cd test-app`
3. Run nightlight `lein nightlight`
4. Go to `http://localhost:4000` and click on the `Clojure REPL` tab
5. The REPL namespace is `clojure.core`

**Comment by Kauko** [comment]
We are interested in using Nightlight at clojure workshops. This feature would make the editor even easier for beginners.

**Comment by oakes** [comment]
Looking into this today. Should be pretty simple, I just forgot about it until now.

**Comment by oakes** [comment]
Just released version 2.4.0 which allows setting the initial namespace. Let me know if you notice any problems.
