### ISSUE TITLE
Global .nightlight.edn

### ISSUE THREAD

**Issue by hswick** [oakes/Nightlight#42]
Similar to how emacs has a ~/.emacs, would be nice to have a global file that nightlight looks for on initialization. Pulls in the keys from that file and merges it with local. Local taking precedence. 

Immediate benefit of this would be you wouldn't need to manually set any preferred settings for every new project. 

The other idea I had was this could be the start for where nightlight 'packages' get hooked in like how the global .emacs file works.

**Comment by oakes** [comment]
If you mean for things like theme, I think it would be better to just allow passing that as an option; then people can set it in their `~/.boot/profile.boot` or `~/.lein/profiles.clj` if they want a global setting. I'll think about that more next time I get a chance.
