### ISSUE TITLE
Client running slow when hosted on remote with lots of nested directories

### ISSUE THREAD

**Issue by hswick** [oakes/Nightlight#43]
Currently working with a project with a lot of text files in nested directories http://www.gutenberg-tar.com/ and finding that the nightlight client runs extremely slow. Will also note that I wasn't trying to access any of these files in the client. Simply was working in my build.boot and core.clj files.

Thought this might be that my vm needed more memory but this turned out to not help. 

Was getting this error on startup when my data directory was included in resource. 

                            java.lang.Thread.run             Thread.java: 748
         sun.nio.fs.LinuxWatchService$Poller.run  LinuxWatchService.java: 329
       sun.nio.fs.AbstractPoller.processRequests     AbstractPoller.java: 260
sun.nio.fs.LinuxWatchService$Poller.implRegister  LinuxWatchService.java: 264
       java.io.IOException: User limit of inotify watches reached
clojure.lang.ExceptionInfo: User limit of inotify watches reached

Maybe increasing this limit on my vm would help. Setting BOOT_WATCHERS_DISABLE=yes, allows me to get pass this error. But it doesn't seem to help nightlight performance.

Thought I should report this because I feel its a good example of a stress test.

**Comment by oakes** [comment]
I just released version 1.9.1 which fixes this issue. Thank you!
