### ISSUE TITLE
Fully-qualified keywords appear as "invalid"

### ISSUE THREAD

**Issue by n2o** [oakes/Nightlight#44]
This issue is related to #2 , but this is a general problem with fully-qualified keywords. They are not correctly interpreted, which is a problem when writing clojure.specs or similar.

![image](https://user-images.githubusercontent.com/1507474/30427597-aa1d52c2-9950-11e7-9fc6-792f362c3070.png)

![image](https://user-images.githubusercontent.com/1507474/30427682-fe0f8404-9950-11e7-8211-acb4802c8815.png)

We tried to use nighlight on a server-installation of a prototype, but all specs are wrongly interpreted in the Web UI, which disturbs the workflow, because everything appears with a red failure-icon.

**Comment by mattiasw2** [comment]
Same problem with (s/def ::aws-access-key-id string?)

**Comment by oakes** [comment]
I finally fixed this issue, and I'll be making a new release today.

**Comment by oakes** [comment]
I have released nightlight 1.9.0 which fixes this issue.

**Comment by ioRekz** [comment]
Hi, I think this is a related error 
![screen shot 2017-12-29 at 15 11 41](https://user-images.githubusercontent.com/688774/34438946-cadc9ec0-ecaa-11e7-95e7-a231b15d062b.png)

events is required as `[nightcoders.events :refer [<sub] :as events])`

the whole project is on nightcoders : 
http://nightcoders.net/1469/1852/code/ file : `form.cljs`

**Comment by oakes** [comment]
Yeah I noticed this recently; it appears that keywords with aliases still show up as an error. The workaround is to write `:nightcoders.events/log` like you do on the line below. I'll re-open this issue and look into it soon.

**Comment by oakes** [comment]
@ioRekz I just released Nightlight 2.1.0 which fixes the remaining aliased keyword issue. I also updated Nightcoders.net with the same fix. Thanks!

**Comment by ioRekz** [comment]
Thanks for the quick fix ! 

Was there some recent changes with how parinfer works ? I feel like it's not closing/moving parens as it used to. Really not sure about it so you can ignore if you didn't notice anything.

**Comment by oakes** [comment]
Not that I know of but if you notice a specific thing that seems wrong feel free to make an issue

**Comment by oakes** [comment]
Not that I know of but if you notice a specific thing that seems wrong feel free to make an issue
