### ISSUE TITLE
Can't get CLJS REPL working

### ISSUE THREAD

**Issue by hswick** [oakes/Nightlight#46]
Hi, I tried using the clojurescript repl as outlined in the documentation and I was having a bit of trouble. I could run `boot run` and then get to the cljs repl page. After pressing start button, the repl wasn't printing anything. And the app said "Not Found".

Here is my build.boot
```clojure
(set-env!
  :resource-paths #{"src"}
  :dependencies '[[org.clojure/clojure "1.9.0-alpha15"]
                  [pandeiro/boot-http "0.8.3" :scope "test"]
                  [adzerk/boot-cljs "1.7.48-5"]
                  [adzerk/boot-reload "0.5.2"]
                  [org.clojure/clojurescript "1.9.946"]
                  [nightlight "1.9.2" :scope "test"]
                  [cljs-web3 "0.19.0-0-7"]])

(require
  '[nightlight.boot :refer [nightlight]]
  '[pandeiro.boot-http :refer [serve]]
  '[adzerk.boot-reload :refer [reload]]
  '[adzerk.boot-cljs :refer [cljs]]
  'web3-test.core)

(deftask night []
  (comp
    (wait)
    (nightlight :port 4000)))

(deftask run []
  (comp
    (serve :dir "target/public" :port 3000)
    (watch)
    (reload)
    (cljs :source-map true :optimizations :none)
    (target)
    (nightlight :port 4000 :url "http://localhost:3000")))
```

I reated a src/web3_test/core.cljs file that looks like this. This could be wrong as I was sort of confused by this.

```clojure
(ns web3-test.core
  (:require [nightlight.repl-server]))
```

**Comment by oakes** [comment]
There should no longer be a "Start" button in 1.9.2. I'm guessing you need to do a force refresh to kill whatever is cached in your browser. Please try that and let me know if you still have a problem.

**Comment by hswick** [comment]
Okay yeah the old version was a mistake on my part. I always forget about the browser cache.

But I still seem to have the issue with the REPL. It is very likely I'm missing a config step.

**Comment by oakes** [comment]
Can I see your `main.cljs.edn` file?

**Comment by hswick** [comment]
Don't have one lol. What is it supposed to look like?

I'll make a boot template for this once I get it running.

**Comment by oakes** [comment]
It's required for boot-cljs. You can put it anywhere in your `resources` folder. Here's an example:

https://github.com/oakes/full-stack-boot-example/blob/master/resources/public/main.cljs.edn

That file will include your core namespace, thus telling boot-cljs where to start when compiling. If you want an easy way to start a project, go to [Nightcoders.net](http://nightcoders.net/). Log in and create a web app, then click the "Export" button. It will download a fully functional boot project in a zip file, with Nightlight already configured.

**Comment by oakes** [comment]
I'll close this ticket but let me know if you need any more help.

**Comment by oakes** [comment]
Did that work for you?

**Comment by hswick** [comment]
Yes mostly, nightcode.net seems really great. I was having an issue with requiring dependency in the repl though, I posted it in the #nightlight slack

**Comment by azureus89** [comment]
@hswick what did you do exactly, I seem to be having the same problem

**Comment by oakes** [comment]
Hey azureus, what problem specifically? Do you mean the iframe doesn't load anything when you select clojurescript repl from the sidebar?
