### ISSUE TITLE
New version on clojars?

### ISSUE THREAD

**Issue by kernelp4nic** [oakes/Nightlight#50]
Hi! I would like to test some things on master, but I don't see any recent version update on clojars.
Any chances to upload a SNAPSHOT version to clojars?

**Comment by oakes** [comment]
I'm not sure what you mean by this. If I upload a SNAPSHOT to clojars, it won't include whatever changes you make to your local copy of Nightlight. Did you mean something else?

**Comment by kernelp4nic** [comment]
oh sorry for the misunderstanding, I was trying to test some changes from Nightlight `master` repo, not my fork. I ended up installing a local version of Nightlight into my maven repo.

Feel free to close this. :)

**Comment by oakes** [comment]
Ah I see. Well 2.1.3 is on clojars and it should have the latest changes in it. But yeah you can always run `boot local` to install it locally.
