### ISSUE TITLE
Can't use lein-nightlight with Leiningen 2.9.0+

### ISSUE THREAD

**Issue by RutledgePaulV** [oakes/Nightlight#54]
Hi Zach,

Leiningen 2.9.0 updated leiningen's default version of Clojure to 1.10.0. This indirectly caused an issue for leiningen plugins using leinjacker because Clojure 1.10 isn't compatible with the version of clojure.unify brought in by clojure.contracts (which leinjacker uses). I'll put up a PR as well but created the issue for context.

See related: 
https://github.com/sattvik/leinjacker/issues/16
https://github.com/weavejester/lein-ring/issues/203

@griffinlacek

**Comment by oakes** [comment]
Merged the PR so this can be closed.
