### ISSUE TITLE
How to integrate with shadow-cljs project?

### ISSUE THREAD

**Issue by divs1210** [oakes/Nightlight#57]

**Comment by oakes** [comment]
I have never used shadow-cljs, sorry. Does it use the jvm at all, or does it run completely on node?

**Comment by divs1210** [comment]
I created a dummy project.clj as described [here](https://shadow-cljs.github.io/docs/UsersGuide.html#_editor_integration), and can now connect to the shadow nREPL via the nightlight plugin.
