### ISSUE TITLE
missing  ring/util/request dep

### ISSUE THREAD

**Issue by barkanido** [oakes/Nightlight#6]
> lein nightlight --port 4000
> Exception in thread "main" java.io.FileNotFoundException: Could not locate ring/util/request__init.class or ring/util/request.clj on classpath., compiling:(nightlight/core.clj:1:1)

**Comment by oakes** [comment]
Can you show me what project you're running it in?

**Comment by barkanido** [comment]
here is project.clj:
(defproject af-matcher "0.1.0"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :uberjar-exclusions [#"^backtype._" #"^defaults.yaml$"]
  :global-vars {_warn-on-reflection\* false}
  :aot :all
  :plugins [[s3-wagon-private "1.1.2"]]
  :repositories [["private" {:url "s3p://clojure-deps/releases/"
                             :username :env/AWS_ACCESS_KEY
                             :passphrase :env/AWS_SECRET_KEY}]]
  :exclusions [org.slf4j/slf4j-simple
               org.slf4j/slf4j-log4j12
               org.slf4j/impl.StaticLoggerBinder]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.apache.httpcomponents/httpcore-nio "4.4"]
                 [af-components "2.2.1"]
                 [org.apache.httpcomponents/httpcore "4.4"]
                 [couchbase-clj "0.2.0" :exclusions [com.couchbase.client/couchbase-client]]
                 [com.couchbase.client/couchbase-client "1.4.12"]
                 [clojurewerkz/spyglass "1.1.0"]
                 [clj-kafka "0.2.6-0.8"]
                 [overtone/at-at "1.2.0"]
                 [cheshire "5.2.0"]
                 [clj-http "2.0.0"]
                 [compojure "1.1.5"]
                 [com.cemerick/url "0.1.1"]
                 [org.clojure/data.codec "0.1.0"]
                 [ring/ring-json "0.3.1"]
                 [clj-time "0.6.0"]
                 [org.clojure/core.match "0.2.2"]
                 [lamina "0.5.2"]
                 [digest "1.4.4"]
                 [byte-transforms "0.1.3"]
                 [aleph "0.3.2"]
                 [zookeeper-clj "0.9.3"]
                 [com.taoensso/timbre "4.1.4"]
                 [org.clojure/core.async "0.1.267.0-0d7780-alpha"]
                 [af-localization-component "0.1.2"]
                 [com.stuartsierra/component "0.3.1"]
                 [mount "0.1.10"]
                 [com.novemberain/langohr "3.6.1"]
                 [com.cemerick/url "0.1.1"]
                 [com.aerospike/aerospike-client "3.2.2"]
                 [af-common-rta-conf "0.0.10"]
                 [af-common-rta-jvm-metrics "0.0.3"]]
  :main af-matcher.system
  :profiles {:library {:aot ^:replace []
                       :main ^:replace ^:skip-aot af-matcher.system
                       :deploy-repositories  {"releases"  {:url "s3p://clojure-deps/releases/"
                                                           :username :env/AWS_ACCESS_KEY
                                                           :passphrase :env/AWS_SECRET_KEY
                                                           :sign-releases false}}
                       :target-path "target/%s"}})

**Comment by oakes** [comment]
Can't test this because it appears to require AWS creds to pull all the deps.
