### ISSUE TITLE
Sluggish performance on larger project

### ISSUE THREAD

**Issue by pesterhazy** [oakes/Nightlight#8]
Very interesting new approach Zach, thanks for working on this!

I tried it with a larger project I'm working on. I see a number of performance issues:
- on startup, it takes 20+ seconds to load what appears to be the project tree (firefox offers to kill the script)
- editing a clojure file with 1000 lines is slow (>2 second delay for some keystrokes)

The repl by contrast seems fine so I suspect it's a javascript-side issue.

**Comment by pesterhazy** [comment]
I'm seeing these issues on both Chrome and Firefox

**Comment by oakes** [comment]
Could you try version 1.3.0 in your project and let me know if you notice any improvement?

**Comment by oakes** [comment]
Closing, but feel free to let me know if it's still an issue with the latest version (currently 1.3.2).
